kind: Service
apiVersion: v1
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017 #// host port, where pod is running
    targetPort: 27017 #// container port
    #nodePort: 30081  #//You’ll be able to contact the NodePort Service, from outside the cluster, by requesting <NodeIP>:<NodePort>.,  a NodePort in the range of 30000 - 32767 and an internal cluster IP address is assigned to the service. specially to expose 
  type: NodePort
