apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  annotations: 
   # prometheus.io/scrape: "true"
   # prometheus.io/path: "/swagger-stats/metrics"
   # prometheus.io/port: "3000"
  labels:
    app: nodeapp
spec:
  containers:
  - name: nodeapp
    image: hmharsh3/myapp:11
    ports:
      - containerPort: 3000
